on:
  push:
    branches:
    - main
    - release/*
jobs:
  test:
    name: Test on node
    runs-on: ubuntu-18.04
  
    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.5.1
